"""widen model_lifecycle_events.triggered_by for admin emails

Revision ID: 16a9117a8fc2
Revises: 4eb6e1bd9a9e
Create Date: 2026-09-20 23:04:14.158684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a9117a8fc2'
down_revision: Union[str, None] = '4eb6e1bd9a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_lifecycle_events', 'triggered_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_lifecycle_events', 'triggered_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
